services:
  elasticsearch:
    build: elasticsearch/
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    user: esuser
    networks:
      - docker_elk
    volumes:
      - $PWD/data/es/:/home/esuser/data  
  logstash:
    build: logstash/
    container_name: logstash
    ports:
      - "5000:5000"
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    user: lsuser
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  kibana:
    build: kibana/
    container_name: kibana
    ports:
      - "5601:5601"
    user: kbuser
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

networks:
  docker_elk:
    driver: bridge
